enable_on_desktop:
  type: bool
  default: false

hide_mobile_combined_button_icon:
  type: bool
  default: false

combined_button_icon:
  type: string
  default: user

login_button_icon:
  type: string
  default: user

signup_button_icon:
  type: string
  default: user-plus
